### ISSUE TITLE
Document what every type is good for

### ISSUE THREAD

**Issue by Wulfheart** [AkrilliA/laravel-beyond#34]
I think it would be really helpful to document what each type of action which can be generated is good for.

**Comment by regnerisch** [comment]
Thanks for your suggestion. Maybe you want to support us with a pull request

**Comment by alexgaal** [comment]
@Wulfheart Does the current README feel more descriptive to you?

**Comment by Wulfheart** [comment]
@alexgaal Yes, it does.
I don't know your goals. If you just develop this for your own benefit then I think the docs are complete.
However, I believe that this package has become something more than an auxiliary package to a book. That's why I think that a more thorough explanation of the concepts is needed. Good documentation is in my opinion key to let the package blow up.

**Comment by regnerisch** [comment]
You are right, this package is not longer just a package for my own usage. As I already said: Feel free to support us with a PR and better docs. Even a little input how you would expect the docs could help us :)

**Comment by Wulfheart** [comment]
I am going to write a draft.

**Comment by regnerisch** [comment]
@Wulfheart do you want to improve the documentation any further? As we are currently developing v7, it can't be a better time to provide better docs ;)

**Comment by Wulfheart** [comment]
I guess I will add an annotation where each command creates something in (App/Domain/Infrastructure). This would help me really much as I am always asking myself where it is generated.

**Comment by Wulfheart** [comment]
What do you prefer? A structure like this:
````md
## Usage

### Commands

#### App

#### Domain

##### `beyond:make:action`

This command will create a new action class inside your domain.

```bash
php artisan beyond:make:action Users.CreateUserAction
```

###### Options

| Name       | Description                                        |
|------------|----------------------------------------------------|
| `--force`  | Create the class even if the action already exists |

---
````
Or something like 
`#### beyond:make:action [Domain]`?  can contribute both if you want to.

**Comment by regnerisch** [comment]
It's your decision :)

**Comment by Wulfheart** [comment]
So no preferences?

**Comment by regnerisch** [comment]
We will use the Github wiki for out documentation: https://github.com/AkrilliA/laravel-beyond/wiki

**Comment by regnerisch** [comment]
As we (again) changed how v7 work, we also again changed the documentation, take a look at `/docs` folder inside the `main` branch. We plan to release v7 next month.
