### ISSUE TITLE
Deptrac integration

### ISSUE THREAD

**Issue by Wulfheart** [AkrilliA/laravel-beyond#38]
Just like #37 based on Ryutu Hamasakis talk at Laracon Online Winter 2022 (https://youtu.be/0Rq-yHAwYjQ?t=5885 -> link now with different timestamp than before):
To seperate the domain boundaries we could use [deptrac](https://github.com/qossmic/deptrac) and maybe add this to the default template. What do you think?

**Comment by Wulfheart** [comment]
It depends. I am not that familiar with the book. How does the communication between domains work? Via Actions?
Is there an open source application which uses this package?

**Comment by alexgaal** [comment]
I don't know any open source application using our package and/or Spaties book. @regnerisch Tell me if I'm wrong but domains mainly communicate via Actions.

**Comment by Wulfheart** [comment]
I am not sure. I don't exactly recall everything from Laravel Beyond Crud. But as far as I recall correctly one shouldn't e.g. use the model of another domain. Am I right about this?

**Comment by alexgaal** [comment]
We'll close this issue since we don't want to add another dependency on the stack. Thank you for your contribution.

**Comment by regnerisch** [comment]
We could ad a command `php artisan beyond:publish:deptrac` with an default config for the new v7 structure. So the users are free to add it to there project or not.

**Comment by regnerisch** [comment]
We now support Deptrac! `php artisan beyond:publish:deptrac` publishes a v7 compatible `deptrac.yaml` file and allows users to enforce architectural decisions by Laravel Beyond.
