### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by Wulfheart** [AkrilliA/laravel-beyond#77]
Where should notifications be placed? In the domain or App layer?

**Comment by alexgaal** [comment]
Hi, I think Notifications should be placed within Domain Layer and will be triggered in your Application layer. @regnerisch Any thoughts about this one?

**Comment by alexgaal** [comment]
Exactly, that's the main reason why I think notifications should live in domain layer. Actions should never require to call something of your application layer but calling a domain class within a domain class is fine in my opinion.

**Comment by regnerisch** [comment]
I put my notifications inside the domain, as you said @Wulfheart. Actions do trigger the notifications (or events/listeners) so this should be the right place.

**Comment by Wulfheart** [comment]
Ok. Thanks. Maybe I am going to contribute a command for generating notifications.

**Comment by alexgaal** [comment]
See #83.
