### ISSUE TITLE
Remove old if/else statements from MakeControllerCommand

### ISSUE THREAD

**Issue by regnerisch** [AkrilliA/laravel-beyond#84]
https://github.com/AkrilliA/laravel-beyond/blob/main/src/Commands/MakeControllerCommand.php#L21..L29

**Comment by bleakprestiger** [comment]
Can i take this enhancement ?

**Comment by bleakprestiger** [comment]
i have already made changes regarding the same.

**Comment by alexgaal** [comment]
Sure, just create a PR @bleakprestiger.

**Comment by bleakprestiger** [comment]
hi @alexgaal, i have opened the Pull Request For the Same.

**Comment by bleakprestiger** [comment]
#85

**Comment by regnerisch** [comment]
Thank you for your contribution!
