### ISSUE TITLE
Incorrect schema method used in migration created by php artisan beyond:make:model -mf

### ISSUE THREAD

**Issue by Wulfheart** [AkrilliA/laravel-beyond#86]
`php artisan beyond:make:model -mf` generates a migration with `Schema::table()`. However, as a new model is created I think it should be `Schema::create()`. May fix this later just putting it out here right now so that I remember.

**Comment by alexgaal** [comment]
See https://github.com/AkrilliA/laravel-beyond/releases/tag/v5.3.2.
