### ISSUE TITLE
i get this issue while install via composer

### ISSUE THREAD

**Issue by atif08** [AkrilliA/laravel-beyond#89]
Problem 1
    - regnerisch/laravel-command-hooks 2.0.0 requires illuminate/console ^9.25 -> found illuminate/console[v9.25.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.
    - akrillia/laravel-beyond[5.4.0, ..., 5.4.1] require regnerisch/laravel-command-hooks ^2.0 -> satisfiable by regnerisch/laravel-command-hooks[2.0.0].
    - Root composer.json requires akrillia/laravel-beyond ^5.4 -> satisfiable by akrillia/laravel-beyond[5.4.0, 5.4.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require akrillia/laravel-beyond:*" to figure out if any version is installable, or "composer require akrillia/laravel-beyond:^2.1" if you know which you need.

**Comment by regnerisch** [comment]
As @Mutahhar mentioned this is because of `regnerisch/laravel-command-hooks`. I updated it this morning, we also have a feature (#88) which removes it completly. We will release a new version shortly

**Comment by alexgaal** [comment]
We just released v6.0.0, which is Laravel 10 ready.
