### ISSUE TITLE
v7.0.0-beta.x feedback

### ISSUE THREAD

**Issue by regnerisch** [AkrilliA/laravel-beyond#92]
- [x] Missing `beyond:make:migration` command
- [x] The given module "Auth}" does not exists. Did you run `php artisan beyond:make:module Auth`?
- [x] Module can not be `--force` overwritten
- [x] #94
- [x] `Illuminate\Contracts\Validation\Rule;` is deprecated use `Illuminate\Contracts\Validation\ValidationRule;`

**Comment by alexgaal** [comment]
> * [x]  Set `--minimal` as default on `beyond:make:module`
> * [x]  Fix missing space on `info`:  `Action[modules/User/Domain/Actions/UserDestroyAction.php] created successfully.`
> * [ ]  Add autoregister for module service providers
> * [x]  Add alias command for `beyond:make:dto` -> `beyond:make:data`

Why not replace `beyond:make:dto` by `beyond:make:data`? Since we are releasing a major version anyways and it's not breaking any existing code only how a Data Object would be created.

**Comment by alexgaal** [comment]
🫡 Good job man.

**Comment by regnerisch** [comment]
- [ ] Missing return type `array` in `resource.stub`

**Comment by Wulfheart** [comment]
Two issues I had:
1. The `beyond:make:module` is missing in the docs and the `--full` option does not explain what it does.
2. It would be nice to automatically place a .gitkeep folder in each directory when generating a module via `--full` as it would not be tracked in version control otherwise.

**Comment by regnerisch** [comment]
1. `--full` creates all possible directories. (Yes docs should be provided)
2. We should discuss this, as i prefer removing empty directories from my version control. 
3. As always: Feel free to add the command :)

**Comment by regnerisch** [comment]
- [ ] Add MakeTestCommand

**Comment by alexanderkroneis** [comment]
[] Command for Scopes

**Comment by regnerisch** [comment]
Closed as we again changed how v7 will work. We try to release v7 next month.
