### ISSUE TITLE
What is the reason for changing the structure in version 7?

### ISSUE THREAD

**Issue by hossein7441** [AkrilliA/laravel-beyond#95]
Hello,
In version 7, you mentioned that changed the way for to ensures compatibility with any other (Laravel related) package.
Can you tell me which packages not compatible with v6 structure or which problems may be happens with it?

**Comment by alexgaal** [comment]
We know that it's tricky to install Jetstream and Laravel Beyond together. At this point we are not aware of any incompatibilities with other packages. v7 is in a pre-release state and has a good test coverage. Feel free to install it by using

```bash
composer require akrillia/laravel-beyond:v7.0.0-beta.4
```

**Comment by regnerisch** [comment]
In v6.x we manipulate the default Laravel structure, which is not the best case for a 3rd party package. So we decided to keep the default structure and change how Beyond works.
